CREATE TABLE IF NOT EXISTS `trade_order`
(
    `id`                      bigint   NOT NULL  AUTO_INCREMENT COMMENT '任务编号',
    `no`                      varchar(64)  NOT NULL,
    `type`                    int      NOT NULL,
    `terminal`                int      NOT NULL,
    `user_id`                 bigint   NOT NULL,
    `user_ip`                 varchar(64)  NOT NULL,
    `user_remark`             varchar(64),
    `status`                  int      NOT NULL,
    `product_count`           int      NOT NULL,
    `cancel_type`             int,
    `remark`                  varchar(64),
    `comment_status`          boolean,
    `brokerage_user_id`       bigint,
    `pay_status`              bit      NOT NULL,
    `pay_time`                datetime,
    `finish_time`             datetime,
    `cancel_time`             datetime,
    `total_price`             int      NULL,
    `order_price`             int      NULL,
    `discount_price`          int      NOT NULL,
    `delivery_price`          int      NOT NULL,
    `adjust_price`            int      NOT NULL,
    `pay_price`               int      NOT NULL,
    `delivery_type`           int      NOT NULL,
    `pay_order_id`            bigint,
    `pay_channel_code`        varchar(64),
    `delivery_template_id`    bigint,
    `logistics_id`            bigint,
    `logistics_no`            varchar(64),
    `delivery_time`           datetime,
    `receive_time`            datetime,
    `receiver_name`           varchar(64)  NOT NULL,
    `receiver_mobile`         varchar(64)  NOT NULL,
    `receiver_area_id`        int      NOT NULL,
    `receiver_post_code`      int,
    `receiver_detail_address` varchar(64)  NOT NULL,
    `pick_up_store_id`        long     NULL,
    `pick_up_verify_code`     varchar(64)  NULL,
    `refund_status`           int      NULL,
    `refund_price`            int      NULL,
    `after_sale_status`       int      NULL,
    `coupon_id`               bigint   NOT NULL,
    `coupon_price`            int      NOT NULL,
    `use_point`               int      NULL,
    `point_price`             int      NOT NULL,
    `give_point`              int      NULL,
    `refund_point`            int      NULL,
    `vip_price`               int      NULL,
    `seckill_activity_id`     long     NULL,
    `bargain_activity_id`     long     NULL,
    `bargain_record_id`       long     NULL,
    `combination_activity_id` long     NULL,
    `combination_head_id`     long     NULL,
    `combination_record_id`   long     NULL,
    `creator`                 varchar(64)           DEFAULT '',
    `create_time`             datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater`                 varchar(64)           DEFAULT '',
    `update_time`             datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted`                 bit      NOT NULL DEFAULT FALSE,
    PRIMARY KEY (`id`)
) COMMENT '交易订单表';

CREATE TABLE IF NOT EXISTS `trade_order_item`
(
    `id`                bigint   NOT NULL  AUTO_INCREMENT COMMENT '任务编号',
    `user_id`           bigint   NOT NULL,
    `order_id`          bigint   NOT NULL,
    `cart_id`           int      NULL,
    `spu_id`            bigint   NOT NULL,
    `spu_name`          varchar(64)  NOT NULL,
    `sku_id`            bigint   NOT NULL,
    `properties`        varchar(64),
    `pic_url`           varchar(64),
    `count`             int      NOT NULL,
    `comment_status`    boolean  NULL,
    `price`             int      NOT NULL,
    `discount_price`    int      NOT NULL,
    `delivery_price`    int      NULL,
    `adjust_price`      int      NULL,
    `pay_price`         int      NOT NULL,
    `coupon_price`      int      NULL,
    `point_price`       int      NULL,
    `use_point`         int      NULL,
    `give_point`        int      NULL,
    `vip_price`         int      NULL,
    `after_sale_id`     long     NULL,
    `after_sale_status` int      NOT NULL,
    `creator`           varchar(64)           DEFAULT '',
    `create_time`       datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater`           varchar(64)           DEFAULT '',
    `update_time`       datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted`           bit      NOT NULL DEFAULT FALSE,
    PRIMARY KEY (`id`)
) COMMENT '交易订单明细表';

CREATE TABLE IF NOT EXISTS `trade_after_sale`
(
    `id`             bigint   NOT NULL  AUTO_INCREMENT COMMENT '任务编号',
    `no`             varchar(64)  NOT NULL,
    `status`         int      NOT NULL,
    `type`           int      NOT NULL,
    `way`            int      NOT NULL,
    `user_id`        bigint   NOT NULL,
    `apply_reason`   varchar(64)  NOT NULL,
    `apply_description` varchar(64),
    `apply_pic_urls` varchar(64),
    `order_id`       bigint   NOT NULL,
    `order_no`       varchar(64)  NOT NULL,
    `order_item_id`  bigint   NOT NULL,
    `spu_id`         bigint   NOT NULL,
    `spu_name`       varchar(64)  NOT NULL,
    `sku_id`         bigint   NOT NULL,
    `properties`     varchar(64),
    `pic_url`        varchar(64),
    `count`          int      NOT NULL,
    `audit_time`     varchar(64),
    `audit_user_id`  bigint,
    `audit_reason`   varchar(64),
    `refund_price`   int      NOT NULL,
    `pay_refund_id`  bigint,
    `refund_time`    varchar(64),
    `logistics_id`   bigint,
    `logistics_no`   varchar(64),
    `delivery_time`  varchar(64),
    `receive_time`   varchar(64),
    `receive_reason` varchar(64),
    `creator`        varchar(64)           DEFAULT '',
    `create_time`    datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater`        varchar(64)           DEFAULT '',
    `update_time`    datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted`        bit      NOT NULL DEFAULT FALSE,
    PRIMARY KEY (`id`)
) COMMENT '交易售后表';

CREATE TABLE IF NOT EXISTS `trade_after_sale_log`
(
    `id`            bigint   NOT NULL  AUTO_INCREMENT COMMENT '任务编号',
    `user_id`       bigint   NOT NULL,
    `user_type`     int      NOT NULL,
    `after_sale_id` bigint   NOT NULL,
    `order_id`      bigint   NOT NULL,
    `order_item_id` bigint   NOT NULL,
    `before_status` int,
    `after_status`  int      NOT NULL,
    `content`       varchar(64)  NOT NULL,
    `creator`       varchar(64)           DEFAULT '',
    `create_time`   datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater`       varchar(64)           DEFAULT '',
    `update_time`   datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted`       bit      NOT NULL DEFAULT FALSE,
    PRIMARY KEY (`id`)
) COMMENT '交易售后日志';

CREATE TABLE IF NOT EXISTS `trade_brokerage_user`
(
    `id`                bigint   NOT NULL  AUTO_INCREMENT COMMENT '任务编号',
    `bind_user_id`      bigint   NOT NULL,
    `bind_user_time`    varchar(64),
    `brokerage_enabled` bit      NOT NULL,
    `brokerage_time`    varchar(64),
    `price`             int      NOT NULL,
    `frozen_price`      int      NOT NULL,
    `creator`           varchar(64)           DEFAULT '',
    `create_time`       datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater`           varchar(64)           DEFAULT '',
    `update_time`       datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted`           bit      NOT NULL DEFAULT FALSE,
    `tenant_id`         bigint   NOT NULL DEFAULT '0',
    PRIMARY KEY (`id`)
) COMMENT '分销用户';
CREATE TABLE IF NOT EXISTS `trade_brokerage_record`
(
    `id`            int      NOT NULL  AUTO_INCREMENT COMMENT '任务编号',
    `user_id`       bigint   NOT NULL,
    `biz_id`        varchar(64)  NOT NULL,
    `biz_type`      varchar(64)  NOT NULL,
    `title`         varchar(64)  NOT NULL,
    `price`         int      NOT NULL,
    `total_price`   int      NOT NULL,
    `description`   varchar(64)  NOT NULL,
    `status`        varchar(64)  NOT NULL,
    `frozen_days`   int      NOT NULL,
    `unfreeze_time` varchar(64),
    `creator`       varchar(64)           DEFAULT '',
    `create_time`   datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater`       varchar(64)           DEFAULT '',
    `update_time`   datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted`       bit      NOT NULL DEFAULT FALSE,
    `tenant_id` bigint not null default '0',
    PRIMARY KEY (`id`)
) COMMENT '佣金记录';
CREATE TABLE IF NOT EXISTS `trade_brokerage_withdraw`
(
    `id`                  int      NOT NULL  AUTO_INCREMENT COMMENT '任务编号',
    `user_id`             bigint   NOT NULL,
    `price`               int      NOT NULL,
    `fee_price`           int      NOT NULL,
    `total_price`         int      NOT NULL,
    `type`                varchar(64)  NOT NULL,
    `name`                varchar(64),
    `account_no`          varchar(64),
    `bank_name`           varchar(64),
    `bank_address`        varchar(64),
    `account_qr_code_url` varchar(64),
    `status`              varchar(64)  NOT NULL,
    `audit_reason`        varchar(64),
    `audit_time`          varchar(64),
    `remark`              varchar(64),
    `creator`             varchar(64)           DEFAULT '',
    `create_time`         datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater`             varchar(64)           DEFAULT '',
    `update_time`         datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted`             bit      NOT NULL DEFAULT FALSE,
    `tenant_id` bigint not null default '0',
    PRIMARY KEY (`id`)
) COMMENT '佣金提现';

CREATE TABLE IF NOT EXISTS `trade_delivery_express`
(
    `id`          int      NOT NULL  AUTO_INCREMENT COMMENT '任务编号',
    `code`        varchar(64)  NULL,
    `name`        varchar(64),
    `logo`        varchar(64)  NULL,
    `sort`        int      NOT NULL,
    `status`      int      NOT NULL,
    `creator`     varchar(64)           DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater`     varchar(64)           DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted`     bit      NOT NULL DEFAULT FALSE,
    PRIMARY KEY (`id`)
) COMMENT '佣金提现';